os:
  - linux
  - osx
language: node_js
node_js:
  - '12'
  - '10'
dist: bionic
sudo: required
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
install:
  - npm set progress=false
  - npm install
script:
  - ng lint
  - npm run test
  - npm run e2e
  - npm run build
